### ISSUE TITLE
The list of tab snapshots is not sorted

### ISSUE THREAD

**Issue by diegomacario** [macadev/Gibbon-Tabs#14]
Dear Papa Van Winkle Apricot Queen,

Here is the situation. This isn't really an issue, it's more of a feature request. The list of tab snapshots is not sorted, which makes it difficult to find the snapshot that you are looking for if you have many. Would it be possible to sort them alphabetically? That would be nice.

Anywho, who this be? The Bee Movie. Co-co-co-cool. Thanks Papa Van Winks.

DeAngelo out.

**Comment by diegomacario** [comment]
Dear Dandee-Gal,

This be De'Arm-Flailer. How do you do my friend? I write you because I looked at the code of this extension to see if I could implement this feature myself, but alas, I only know Perl and Assembly. As such, I request your assistance. Could you point me to the place where changes would need to be implemented?

Anyhow, how's the soup? I'm gonna have to take my shirt off to finish this Chupe, because I be sweltering out here.

P.S. If ya'll don't provide assistance, I am going to have to drop an Uzi down some stairs like Jamie Lee Curtis in True lies. Ya'll know how that ended up.

DeFlailer out.

**Comment by macadev** [comment]
-- DDandy'O'Hare out here,

I hear you about those chupe's - much like the time I had me a ristorante straight outta the oven. God damn, gotta wait at least 2 minutes before flying that saucer into my stomach. Much like driving a car with heating on the steering wheel, except the heating goes up to 425 F.

Anywho, this project is such a spaghetti-o that they could start a new brand of spaghetti with its name. At restaurants you'll be able to choose classics such as "Bow-Tie", "Penne", "Ravioli" and now "Gibbon-Tabs-Angel-Hair". Plenty of reasons to be proud of "Gibbon-Tabs-Angel-Hair" though.

For this change ya'll should start looking here: https://github.com/macadev/Gibbon-Tabs/blob/master/js/snapshot.js#L53-L63

Dandy-O-Mac decided to make that function recursive in 2017, which today seems like a horrendous decision. Notice in the conditional that it calls the "returnCallback" function with a parameter called "listOfSnapshots". That parameter is an array containing the unsorted snapshots. The code of the "returnCallback" function is defined here: https://github.com/macadev/Gibbon-Tabs/blob/master/js/snapshot.js#L303-L337

Ya'll need to write a simple function to sort the array based on the name property of each object. I recommend you do this in the conditional I mentioned above. Then anyone who tries to obtain snapshots will get a sorted list. Or ya'll could let the client that calls getTabSnapshots() do the sorting. I think it would be nice for the client to not have to do this though. Use them console.log() calls to print the array so you understand what's in it. You can see the output in the chrome developer console.

Chicago'O'Hare outta here though.
Give this project some TLC if possible ("Tender Love and Care" not "Tender Licking Chicken").

Best,
Chicago'SOS'O'Hare-MacDanddyy.

**Comment by macadev** [comment]
-- DDandy'O'Hare'laGuardia out here,

Dear De-arm-flailer, 

It's been almost two years since we corresponded about Chupe, Ristorantes, and Jamie Lee Curtis. I spent the last 600 days contemplating how to best implement the simple looking 'tab snapshot sorting' feature. Untangling the recursion monster I created has taken taken it's toll on my desire to be a software developer. Good lord, I wish I knew about JavaScript promises in 2016.

Ripley's believe it or not® I have implemented and released tab snapshot sorting. In fact, I reimplemented the whole codebase so it's no longer a sphagetti mess. My JavaScript knowledge has gone from crapshoot to crapshoot++.

Anywho, just wanted to give you the latest and greatest in the world of competitive carpentry.

Wishing you don't slide down a dry waterslide, this is not a threat, and a ristorante-hot embrace,
DDandy'O'Hare'laGuardia-Maiquetia'Hidalgo'TimewaveZero
