### ISSUE TITLE
Should highlight the current tab on popup open

### ISSUE THREAD

**Issue by bendtherules** [macadev/Gibbon-Tabs#4]

**Comment by macadev** [comment]
@bendtherules, correct me if I'm wrong, you're saying that you would like to see the currently active tab in the list of tabs in the extension. Could you tell me why you want the current tab to be shown? I removed it by default simply because there's no need to search for it since you're looking at it. It will still be included in a tab snapshots.

**Comment by bendtherules** [comment]
Yes, what I would like is to have a list of (all the tabs open) in the same order alongwith the current one with the current one highlighted and in focus.

What I mean is something like this - if Tab A,B,C,D are open with B being current tab, I would like this list  (* means selected) -
1. Tab A
2. Tab B*
3. Tab C
4. Tab D

instead of the current one, which is - 
1. Tab A*
2. Tab C
3. Tab D

How it would help is - Because the current tab is selected, it gives me context about the neighbouring tabs, so if I just press down twice and enter, it would actually go to the second next tab (eg. tab D here)

**Comment by macadev** [comment]
Latest commit adds a shortcut that does what you request. When you press the 'ctrl' key the currently active tab of the active window will be highlighted. I'll push this to the Chrome Store tomorrow along with a few other improvements! 👍 

Thanks for the suggestion! This is a pretty neat feature.

**Comment by bendtherules** [comment]
Thanks for the speedy implementation.
